/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    workers: Worker;
    'business-hours': BusinessHour;
    'schedule-overrides': ScheduleOverride;
    customers: Customer;
    appointments: Appointment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    workers: WorkersSelect<false> | WorkersSelect<true>;
    'business-hours': BusinessHoursSelect<false> | BusinessHoursSelect<true>;
    'schedule-overrides': ScheduleOverridesSelect<false> | ScheduleOverridesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Duration in minutes. Please note that the time slot depends on the service length
   */
  duration: number;
  /**
   * Price in NOK
   */
  price: number;
  /**
   * Whether this service is available for booking
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workers".
 */
export interface Worker {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Profile image for this worker
   */
  profileImage?: (string | null) | Media;
  /**
   * Services this worker can provide
   */
  services?: (string | Service)[] | null;
  /**
   * Working hours for each day of the week
   */
  workingHours?:
    | {
        dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Start time in HH:MM format (24-hour)
         */
        startTime: string;
        /**
         * End time in HH:MM format (24-hour)
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this worker is available for booking
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-hours".
 */
export interface BusinessHour {
  id: string;
  dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  /**
   * Opening time in HH:MM format (24-hour)
   */
  openTime?: string | null;
  /**
   * Closing time in HH:MM format (24-hour)
   */
  closeTime?: string | null;
  /**
   * Check if business is closed on this day
   */
  isClosed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Override regular business hours for specific dates (holidays, special events, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-overrides".
 */
export interface ScheduleOverride {
  id: string;
  /**
   * The specific date for this override
   */
  date: string;
  /**
   * Reason for the schedule change
   */
  reason: string;
  /**
   * Check if the business is completely closed on this date
   */
  isClosed?: boolean | null;
  /**
   * Optional: multiple open blocks (e.g., 08:00–12:00 and 14:00–17:00). If empty, the single open/close time below is used.
   */
  timeRanges?:
    | {
        /**
         * Start time in HH:MM format
         */
        startTime: string;
        /**
         * End time in HH:MM format
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Single opening time if open with different hours (HH:MM format). Leave empty if using time ranges above.
   */
  openTime?: string | null;
  /**
   * Single closing time if open with different hours (HH:MM format). Leave empty if using time ranges above.
   */
  closeTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer records for booking management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  /**
   * The customer making this appointment
   */
  customer: string | Customer;
  /**
   * Select a service first, then choose a worker
   */
  service: (string | Service)[];
  /**
   * Only active workers are shown. Service compatibility is validated automatically on save.
   */
  worker: string | Worker;
  appointmentDate: string;
  /**
   * Time in HH:MM format (24-hour)
   */
  appointmentTime: string;
  status: 'confirmed' | 'completed' | 'cancelled';
  /**
   * Additional notes or special requests
   */
  notes?: string | null;
  /**
   * Secure token for customer cancellation (automatically generated)
   */
  cancellationToken?: string | null;
  /**
   * Email notification tracking (automatically managed)
   */
  emailsSent?: {
    /**
     * Customer confirmation email sent
     */
    confirmationSent?: boolean | null;
    confirmationSentAt?: string | null;
    /**
     * Business notification email sent
     */
    businessNotificationSent?: boolean | null;
    businessNotificationSentAt?: string | null;
    /**
     * Reminder email sent
     */
    reminderSent?: boolean | null;
    reminderSentAt?: string | null;
    /**
     * Cancellation email sent
     */
    cancellationSent?: boolean | null;
    cancellationSentAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'workers';
        value: string | Worker;
      } | null)
    | ({
        relationTo: 'business-hours';
        value: string | BusinessHour;
      } | null)
    | ({
        relationTo: 'schedule-overrides';
        value: string | ScheduleOverride;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  duration?: T;
  price?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workers_select".
 */
export interface WorkersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  profileImage?: T;
  services?: T;
  workingHours?:
    | T
    | {
        dayOfWeek?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-hours_select".
 */
export interface BusinessHoursSelect<T extends boolean = true> {
  dayOfWeek?: T;
  openTime?: T;
  closeTime?: T;
  isClosed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-overrides_select".
 */
export interface ScheduleOverridesSelect<T extends boolean = true> {
  date?: T;
  reason?: T;
  isClosed?: T;
  timeRanges?:
    | T
    | {
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  openTime?: T;
  closeTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  customer?: T;
  service?: T;
  worker?: T;
  appointmentDate?: T;
  appointmentTime?: T;
  status?: T;
  notes?: T;
  cancellationToken?: T;
  emailsSent?:
    | T
    | {
        confirmationSent?: T;
        confirmationSentAt?: T;
        businessNotificationSent?: T;
        businessNotificationSentAt?: T;
        reminderSent?: T;
        reminderSentAt?: T;
        cancellationSent?: T;
        cancellationSentAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}